djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
] \
             + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
             + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import re_path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    re_path(r'^$', views.start, name='start'),
    re_path(r'^order/$', views.order, name='order'),
    re_path(r'^register/$', views.RegisterFormView.as_view(), name='register'),
    re_path(r'^search/register/$', views.RegisterFormView.as_view(), name='register'),
    re_path(r'^login/$', views.LoginFormView.as_view(), name="login"),
    re_path(r'^logout/$', views.LogoutView.as_view(), name="logout"),
    re_path(r'^jackets/$', views.jackets, name='jackets'),
    re_path(r'^siuts/$', views.siuts, name='siuts'),
    re_path(r'^search/$', views.SearchResultsView.as_view(), name="search"),
    re_path(r'^product/(?P<product_id>\w+)/$', views.product, name='product'),
    re_path(r'^product/(?P<product_id>\w+)/feedback/$', views.MyFeedback.as_view(), name="feedback"),
    re_path(r'^search/feedback/$', views.MyFeedback.as_view(), name="feedback"),
    re_path(r'^product/(?P<product_id>\w+)/register/$', views.RegisterFormView.as_view(), name='register'),

]

shop/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "%s" % (self.name)

    class Meta:
        verbose_name = "Категорія товару"
        verbose_name_plural = "Категорія товарів"


class Product(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    discount = models.IntegerField(default=0)
    category = models.ForeignKey(ProductCategory, blank=True, null=True, default=None, on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s %s" % (self.price, self.name)

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товари"


class ProductImage(models.Model):
    product = models.ForeignKey(Product, blank=True, null=True, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products_images/')
    is_main = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.id

    class Meta:
        verbose_name = "Фото"
        verbose_name_plural = "Фото"


class Order(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=128)

    def __str__(self):
        return "Користувач %s %s" % (self.name, self.email)

    class Meta:
        verbose_name = "Замовлення"
        verbose_name_plural = "Замовлення"

shop/forms.py
from django import forms
from .models import *


class OrderForm(forms.ModelForm):

   class Meta:
      model = Order
      exclude =[""]


class FeedbackForm(forms.Form):
   email = forms.EmailField(initial="admin@admin.com", label='Залиште вашу електронну адресу')
   phone = forms.CharField(max_length=10, label='Залиште ваш номер телефону')
   review = forms.CharField(widget=forms.Textarea, label='Залиште ваш відгук')
   grade = forms.ChoiceField(required=False, choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5")],
                             label='Оберіть оцінку')
   general_feedback = forms.ChoiceField(required=False, choices=[("1", "Позитивне"), ("2", "Негативне")],
                                        label='Загальне враження')

shop/views.py
from django.shortcuts import render
from .forms import OrderForm
from django.views.generic import TemplateView
from django.contrib.auth.forms import AuthenticationForm
from .models import *
from django.views.generic.base import View
from .forms import FeedbackForm
from django.views.generic.edit import FormView
from django.http import HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth import logout

def product(request, product_id):
    product = Product.objects.get(id=product_id)

    return render(request, 'products/product.html', locals())


class MyFeedback(FormView):
    form_class = FeedbackForm
    template_name = "products/feedback.html"

    def get(self, request, *args, **kwargs):
        print(request.GET)
        return super().get(request, *args, **kwargs)


class SearchResultsView(TemplateView):
    model = Product

    def post(self, request):
        query = request.POST['search']
        result_list = Product.objects.filter(name__contains=query)
        if result_list.count() != 0:
            context = {
                'result_list': result_list,
                'query': query,
            }
        else:
            context = {
                'empty': "Ничего не найдено",
                'query': query,
            }
        return render(request, 'search_result.html', context)


def order(request):
    form = OrderForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        print(request.POST)
        print(form.cleaned_data)

        form = form.save()

    return render(request, 'order.html', locals())


def start(request):
    products_images = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active=True)
    products_images_jackets = products_images.filter(product__category__id=1)
    products_images_suits = products_images.filter(product__category__id=2)
    return render(request, 'start.html', locals())


def jackets(request):
    products_images = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active=True)
    products_images_jackets = products_images.filter(product__category__id=1)
    products_images_suits = products_images.filter(product__category__id=2)
    return render(request, 'products/jackets.html', locals())


def siuts(request):
    products_images = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active=True)
    products_images_jackets = products_images.filter(product__category__id=1)
    products_images_suits = products_images.filter(product__category__id=2)
    return render(request, 'products/siuts.html', locals())


class RegisterFormView(FormView):
    form_class = UserCreationForm
    success_url = "/login/"
    template_name = "register.html"

    def form_valid(self, form):
        form.save()
        return super(RegisterFormView, self).form_valid(form)

    def form_invalid(self, form):

        return super(RegisterFormView, self).form_invalid(form)

class LoginFormView(FormView):
    form_class = AuthenticationForm
    template_name = "login.html"
    success_url = '/'

    def form_valid(self, form):
        self.user = form.get_user()

        login(self.request, self.user)
        return super(LoginFormView, self).form_valid(form)

class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect('/')

shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css">

    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'static_dev/base.css' %}">

</head>
<body>

    <div class="wrapper">
        <div class="wrapper-content">

            {% include 'navbar.html' %}

            {% block content %}
            {% endblock content %}
        </div>

    </div>

     {% include 'footer.html' %}

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

</body>
</html>

shop/templates/footer.html
<footer class="footer">
    <div class="container">
        <div class="text">
            <h3>MADE WITH LOVE</h3>
        </div>
    </div>
</footer>

shop/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <link rel="stylesheet" href="{% static 'static_dev/feedback.css' %}">

    <div class="general-container">
        <div class="container top-container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <h1 class="title">Доброго дня!<br>
                    Увійдіть до Вашого облікового запису</h1>
                    <div>
                        <form action="" method="post">
                            {% csrf_token %}
                            {% for field in form %}
                            <label for="">{{ field.label }}</label>
                            <div>{{ field }}</div>
                            {% if field.errors %}
                            <p>{{ field.errors }}</p>
                            {% endif %}
                            {% endfor %}

                            <input name='register' type='submit' value="Увійти" class="btn btn-primary btn-orange"></input>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

shop/templates/navbar.html
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
      <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar" >
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">CLOTHES FOR YOU</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
              <li class="active"><a href="/">Головна сторінка</a></li>
              {% if user.is_authenticated %}
              <li class="active"><a href="/logout/">Вийти({{user.username}})</a></li>
              {% else %}
              <li class="active"><a href="/login/">Увійти</a></li>
              {% endif %}
              <li class="active"><a href="/register/">Зареєструватись</a></li>
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Категорії <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                      <li><a href="/jackets/">Куртки</a></li>
                      <li><a href="/siuts/">Костюми</a></li>
                  </ul>
              </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
              <Li>
                  <div class="search-container">
                      <form action="/search/" method="post" class="form-inline my-2 my-lg-0">
                          {% csrf_token %}
                          <input name='search' type="text" class="form-control mr-sm-2" placeholder="Пошук" aria-label="Search">
                          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Пошук</button>
                      </form>
                  </div>
              </Li>
              <li>
                  <div class="basket-container">
                      <a href="/order/">Оформити замовлення</a>
                  </div>
              </li>
          </ul>
      </div><!--|.nav-collapse -->
  </div>
</nav>

shop/templates/order.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <link rel="stylesheet" href="{% static 'static_dev/pages.css' %}">

    <div class="general-container">
        <div class="container top-container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <h1 class="title">Ласкаво просимо до магазину!<br>
                    Для оформлення замовлення залиште Ваші контактні данні і ми обов'язково з Вами зв'яжемся</h1>
                    <div>
                        <form action="" method="post" class="form-inline text-center">{%  csrf_token %}
                            <div class="form-group">
                                <label>Ваше ім'я: </label>
                                <input type="text" name="{{ form.name.name }}" class="form-control">
                            </div>
                            <div class="form-group">
                                <label>Ваш мейл: </label>
                                <input type="text" name="{{ form.email.name }}" class="form-control">
                            </div>
                            <button type="submit" class="btn btn-primary btn-orange">Відправити</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

shop/templates/product_item.html
<div class="col-lg-3">
    <div class="product-item">
        <div>
            <a href="{% url 'product' product_image.product.id %}">
                <img src="{{ product_image.image.url }}" class="img-responsive" alt="shopping">
            </a>
        </div>

        {% if product_image.product.discount %}
            <div class="discount-container">
                <span>{{ product_image.product.discount }}%</span>
            </div>
        {% endif %}

        <h4>{{ product_image.product.name }}</h4>
        <p>
            {{ product_image.product.description }}
        </p>
        <div>
            {{ product_image.product.price }} UAH
        </div>
        <div class="add-to-cart-btn">
            <form action="/order/" target="_blank">
                <button class="btn btn-success">
                    Замовити
                </button>
            </form>
        </div>
    </div>
</div>

shop/templates/products/feedback.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <link rel="stylesheet" href="{% static 'static_dev/feedback.css' %}">

    <div class="general-container">
        <div class="container top-container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <h1 class="title">Доброго дня!<br>
                    Тут ви можете залишити ваш відгук:</h1>
                    <div>
                        <form action="" method="post" class="form-control-static">{%  csrf_token %}
                            <div class="form-group">
                                {{ form.as_p  }}
                            </div>
                            <button type="submit" class="btn btn-primary btn-orange">Підтвердити</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

shop/templates/products/jackets.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="section2 jackets-container">
        <div class="container">
           <div class="row">
                <div class="col-lg-12">
                    <h1 class="text-center">
                        Куртки
                    </h1>
                </div>
               {% for product_image in products_images_jackets %}
                   {% include 'product_item.html' %}
               {% endfor %}
           </div>
        </div>
    </div>
{% endblock content %}

shop/templates/products/product.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                {% for image_item in product.productimage_set.all %}
                    <div class="product-image-item">
                        <img src="{{ image_item.image.url }}" class="img-thumbnail" alt="clothes">
                    </div>
                {% endfor %}
            </div>
            <div class="col-lg-6">
                <h1 class="text-center">
                    {{ product.name }}
                </h1>
                <div class="">
                    <p>
                        Ціна: {{ product.price }}
                    </p>
                </div>
                <div>
                      <!-- Nav tabs -->
                      <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active">
                            <a href="#description" aria-controls="home" role="tab" data-toggle="tab">
                                Опис товару
                            </a>
                        </li>
                        <li role="presentation">
                            <a href="#delivery" aria-controls="profile" role="tab" data-toggle="tab">
                                Доставка
                            </a>
                        </li>
                        <li role="presentation">
                            <a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">
                                Залишити відгук
                            </a>
                        </li>
                      </ul>

                      <!-- Tab panes -->
                      <div class="tab-content product-description-tabs">
                        <div role="tabpanel" class="tab-pane active" id="description">
                            {{ product.description }}
                            <div>
                                <div class="form-group">
                                    <form action="/order/" target="_blank">
                                        <button type="submit" id="submit-btn" class="btn btn-success btn-buy"
                                                data-product_id = "{{ product_id }}"
                                                data-name = "{{ product.name }}"
                                                data-price = "{{ product.price }}"
                                        >Замовити
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div role="tabpanel" class="tab-pane" id="delivery">
                            <h5>Тут будуть описані умови доставки</h5>
                        </div>
                        <div role="tabpanel" class="tab-pane" id="messages">
                            <button type="submit" class="btn btn-success btn-feedback">
                                {% if user.is_authenticated %}
                                <a href="feedback/">Хочу залишити відгук про товар</a>
                                {% else %}
                                <a href="register/">Хочу залишити відгук про товар</a>
                                {% endif %}
                            </button>
                        </div>
                      </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

shop/templates/products/siuts.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="section3 suits-container">
        <div class="container">
           <div class="row">
                <div class="col-lg-12">
                    <h1 class="text-center">
                        Спортивні костюми
                    </h1>
                </div>
               {% for product_image in products_images_suits %}
                   {% include 'product_item.html' %}
               {% endfor %}
           </div>
        </div>
    </div>
{% endblock content %}

shop/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <link rel="stylesheet" href="{% static 'static_dev/feedback.css' %}">

    <div class="general-container">
        <div class="container top-container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <h1 class="title">Доброго дня!<br>
                    Реєстрація на сайті </h1>
                    <div>
                        <form action="" method="post">
                            {% csrf_token %}

                            {% for field in form %}
                            <label for="">{{ field.label }}</label>
                            <div>{{ field }}</div>
                            {% if field.errors %}
                            <p>{{ field.errors }}</p>
                            {% endif %}
                            {% endfor %}

                            <input name='register' type='submit' value="Зареєструватись" class="btn btn-primary btn-orange"></input>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

shop/templates/search_result.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="section4">
    {% for elem in result_list %}
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    {% for image_item in elem.productimage_set.all %}
                        <div class="product-image-item">
                            <img src="{{ image_item.image.url }}" class="img-thumbnail" alt="clothes">
                        </div>
                    {% endfor %}
                </div>
                <div class="col-lg-6">
                    <h1 class="text-center">
                        {{ elem.name }}
                    </h1>
                    <div class="">
                        <p>
                            Ціна: {{ elem.price }}
                        </p>
                    </div>
                    <div>
                      <!-- Nav tabs -->
                        <ul class="nav nav-tabs" role="tablist">
                            <li role="presentation" class="active">
                                <a href="#description" aria-controls="home" role="tab" data-toggle="tab">
                                    Опис товару
                                </a>
                            </li>
                            <li role="presentation">
                                <a href="#delivery" aria-controls="profile" role="tab" data-toggle="tab">
                                    Доставка
                                </a>
                            </li>
                            <li role="presentation">
                                <a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">
                                    Залишити відгук
                                </a>
                            </li>
                        </ul>

                      <!-- Tab panes -->
                        <div class="tab-content product-description-tabs">
                            <div role="tabpanel" class="tab-pane active" id="description">
                                {{ elem.description }}
                                <div>
                                    <div class="form-group">
                                        <form action="/order/" target="_blank">
                                            <button type="submit" id="submit-btn" class="btn btn-success btn-buy"
                                                    data-product_id = "{{ product_id }}"
                                                    data-name = "{{ product.name }}"
                                                    data-price = "{{ product.price }}"
                                            >Замовити
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <div role="tabpanel" class="tab-pane" id="delivery">
                                <h5>Тут будуть описані умови доставки</h5>
                            </div>
                            <div role="tabpanel" class="tab-pane" id="messages">
                                <button type="submit" class="btn btn-success btn-feedback">
                                    {% if user.is_authenticated %}
                                        <a href="/search/feedback/">Хочу залишити відгук про товар</a>
                                    {% else %}
                                        <a href="/search/register/">Хочу залишити відгук про товар</a>
                                    {% endif %}
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock content %}

shop/templates/start.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="section-top">
        <img src ="{% static 'static_dev/img/odezhda.jpg' %}" class="item_modified" alt="shopping">
    </div>

    <div class="section1">
        <div class="container">
           <div class="row">
                <div class="col-lg-12">
                    <h1 class="text-center">
                        Нові надходження
                    </h1>
                </div>
               {% for product_image in products_images %}
                   {% include 'product_item.html' %}
               {% endfor %}
            </div>
        </div>
    </div>

    <div class="section2 jackets-container">
        <div class="container">
           <div class="row">
                <div class="col-lg-12">
                    <h1 class="text-center">
                        Куртки
                    </h1>
                </div>
               {% for product_image in products_images_jackets %}
                   {% include 'product_item.html' %}
               {% endfor %}
           </div>
        </div>
    </div>
    <div class="section3 suits-container">
        <div class="container">
           <div class="row">
                <div class="col-lg-12">
                    <h1 class="text-center">
                        Спортивні костюми
                    </h1>
                </div>
               {% for product_image in products_images_suits %}
                   {% include 'product_item.html' %}
               {% endfor %}
           </div>
        </div>
    </div>
{% endblock content %}